import Head from "next/head";
import Image from "next/image";

import {
  Box,
  Container,
  Flex,
  Heading,
  Text,
  Divider,
  Span,
  Link as ChakraLink,
} from "@chakra-ui/react";
import AuthLogin from "../components/Auth/AuthLogin";
import Link from "next/link";

export default function Login() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        maxWidth="100%"
        height="100vh"
        display="flex"
        justifyContent="center"
        alignItems="center"
      >
        <Box
          display="flex"
          alignItems="center"
          borderRadius="md"
          boxShadow={["", "", "", "xl"]}
          h={["100%", "100%", "100%", "2xl"]}
          w={["100%", "100%", "100%", "75%"]}
        >
          <Box
            height="100%"
            borderRadius="md"
            width="50%"
            display={["none", "none", "none", "inline", "inline", "inline"]}
            background="yellow.400"
            p="12"
            position="relative"
            zIndex="500"
          >
            <Box display="flex" justifyContent="center">
              <Box w="5em">
                <Image
                  src="/assets/img/EROR.png"
                  alt="Logo"
                  width="100%"
                  height="100%"
                />
              </Box>
              <Box
                position="absolute"
                width="96"
                height="96"
                background="gray.100"
                borderRadius="full"
                zIndex="-500"
                mt="10"
                boxShadow="dark-lg"
              ></Box>
              <Box px="5">
                <Heading fontSize="2em" color="gray.800">
                  E-ROR
                </Heading>
                <Heading fontSize="1.3em" color="yellow.500">
                  <Box as="span" color="gray.600" pr="2">
                    Electronic-Request For Repair
                  </Box>
                </Heading>
              </Box>
            </Box>
            <Box
              as="object"
              type="image/svg+xml"
              data="/assets/svg/electrical.svg"
              maxW="100%"
              height="96"
            ></Box>
            <Box>
              <Text fontSize="1.2em" color="gray.600" fontWeight="semibold">
                Electronic - Request For Repair
              </Text>
              <Heading fontSize="1.5em" color="gray.900">
                Solusi untuk penanganan kerusakan sarana dan prasarana.
              </Heading>
            </Box>
          </Box>
          <Box w={["100%", "100%", "100%", "50%"]} mx="auto" my="40" p="10">
            <Heading as="h1" size="lg" color="yellow.400">
              Login ke E-ROR
            </Heading>
            <Text fontSize="lg" py="5" color="yellow.100">
              Masukan kelengkapan data anda.
            </Text>
            <Divider mt="5" mb="10" />
            <AuthLogin />
            <Box textAlign="center" my="5">
              <Box as="span">Lupa password?</Box>
              <ChakraLink
                px="2"
                color="yellow.400"
                href="/register"
                _hover={{ textDecor: "none" }}
                fontWeight="700"
              >
                Reset
              </ChakraLink>
            </Box>
            <Divider mt="5" mb="5" />
            <Box textAlign="center">
              <Box as="span">Belum punya akun?</Box>
              <ChakraLink
                px="2"
                color="yellow.400"
                href="/register"
                _hover={{ textDecor: "none" }}
                fontWeight="700"
              >
                Daftar
              </ChakraLink>
            </Box>
          </Box>
        </Box>
      </Container>
    </div>
  );
}
